---
abstract: 'Buga buga text encode'
author:
  - 'Daniel Vinciguerra <daniel.vinciguerra@bivee.com.br>'
build_requires:
  FindBin: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Buga
requires:
  Convert::BaseN: 0
  Exporter: 0
  constant: 0
  strict: 0
  warnings: 0
version: 1.002
